### ISSUE TITLE
Where does ringbuffer come from?

### ISSUE THREAD

**Issue by chrisdickinson** [indutny/uv_ssl_t#1]
Hey — I was looking at tooling this library up with gn, and I was wondering: where does `ringbuffer` come from?

**Comment by indutny** [comment]
It lives here: https://github.com/indutny/uv_ssl_t/blob/master/deps/ringbuffer/ringbuffer.h , and is something that I have wrote long time ago. We use C++ analog of it in Node.

**Comment by indutny** [comment]
Now it comes from gypkg repo: https://github.com/gypkg/ringbuffer
